language: python
python: 3.8

before_install:
  # make depends on poetry
  - pip install poetry
  - pip install pytest-cov
  - pip install PyYAML

install:
  - make install

script:
  - make lint
  - make test